name: lamaa_cleaning
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:        # ğŸ‘ˆ must be a sibling of `flutter`, not inside it
    sdk: flutter

  cupertino_icons: ^1.0.8
  cloud_firestore: ^6.1.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.0.0
  # firebase_storage: ^13.0.4
  file_picker: ^8.0.0
  cloud_functions: ^6.0.4
  intl: ^0.20.2
  url_launcher: ^6.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
